CREATE TABLE Flowers (
    Flower_Name VARCHAR(100) PRIMARY KEY,
    Gardening_Staff INT,
    Manager_ID INT,
    Type VARCHAR(50),
    Colour VARCHAR(30),
    Fragrance VARCHAR(20) CHECK (Fragrance IN ('Strong', 'Mild', 'None')),
    Quantity INT,
    FOREIGN KEY (Gardening_Staff) REFERENCES Gardening_Staff_Info(Staff_ID),
    FOREIGN KEY (Manager_ID) REFERENCES Sales_Manager(Manager_ID),
    FOREIGN KEY (Type) REFERENCES Flower_Type(Type)
);

INSERT INTO Flowers (Flower_Name, Gardening_Staff, Manager_ID, Type, Colour, Fragrance, Quantity) VALUES
('Champo', 1, 1, 'Fragrant', 'Yellow', 'Strong', 150),
('Mogro', 3, 2, 'Fragrant', 'White', 'Strong', 200),
('Gulad', 43, 3, 'Fragrant', 'Red', 'Strong', 180),
('Desi Gulab', 45, 4, 'Fragrant', 'Pink', 'Strong', 220),
('Jui', 85, 5, 'Fragrant', 'White', 'Strong', 160),
('Jasud', 87, 6, 'Fragrant', 'White', 'Strong', 190),
('Rajnigandha', 127, 7, 'Fragrant', 'White', 'Strong', 140),
('Kaner', 129, 8, 'Ornamental', 'Pink', 'Mild', 300),
('Genda', 169, 9, 'Annual', 'Orange', 'Mild', 250),
('Aboli', 171, 10, 'Perennial', 'Red', 'None', 180),
('Parijat', 211, 11, 'Fragrant', 'White', 'Strong', 120),
('Shevanti', 213, 12, 'Seasonal', 'Yellow', 'Mild', 200),
('Kadamb', 253, 13, 'Fragrant', 'Yellow', 'Strong', 110),
('Bakul', 255, 14, 'Fragrant', 'White', 'Strong', 130),
('Harsingar', 295, 15, 'Fragrant', 'White', 'Strong', 100),
('Raat Rani', 297, 16, 'Fragrant', 'White', 'Strong', 90),
('Kewda', 337, 17, 'Fragrant', 'White', 'Strong', 80),
('Chameli', 339, 18, 'Fragrant', 'White', 'Strong', 170),
('Bela', 379, 19, 'Fragrant', 'White', 'Strong', 160),
('Kanher', 381, 20, 'Ornamental', 'White', 'Mild', 280),
('Galgoto', 1, 21, 'Ornamental', 'Red', 'None', 320),
('Sadabahar', 3, 22, 'Perennial', 'Pink', 'None', 400),
('Aparajita', 43, 23, 'Perennial', 'Blue', 'None', 350),
('Kohinoor', 45, 24, 'Annual', 'Purple', 'None', 270),
('Chandni', 85, 25, 'Fragrant', 'White', 'Strong', 150);
