CREATE TABLE Gardening_Staff_Duty (
    Staff_ID INT NOT NULL,
    Duty_Type VARCHAR(50) NOT NULL,
    Assigned_Area VARCHAR(50) NOT NULL CHECK (Assigned_Area IN (
        'Lecture Theatre area',
        'CEP Area',
        'Administrative Block area',
        'Lab Area',
        'Sports Complex area',
        'Cafeteria Zone',
        'Hor-Men (Old) area',
        'Hor-Men (New) Area',
        'Hor_women Area',
        'Library Complex',
        'Lotus Point Area',
        'Main Gate Area',
        'Parking Area',
        'Faculty Quarters',
        'Guest House',
        'Medical Center',
        'Garden Area',
        'Main Road',
        'Internal Roads',
        'Boundary Wall Area',
        'Security Post Area',
        'Recreation Area',
        'Open Lawn',
        'Tree Plantation Zone',
        'Flower Garden',
        'Vegetable Garden',
        'Greenhouse Area',
        'Compost Area'
    )),
    Shift_Time VARCHAR(20) NOT NULL CHECK (Shift_Time IN ('morning', 'evening', 'night')),
    PRIMARY KEY (Staff_ID, Duty_Type, Assigned_Area),
    FOREIGN KEY (Staff_ID) REFERENCES Gardening_Staff_Info(Staff_ID),
    FOREIGN KEY (Duty_Type) REFERENCES Duty_Info(Duty_Type)
);


INSERT INTO Gardening_Staff_Duty (Staff_ID, Duty_Type, Assigned_Area, Shift_Time) VALUES
(1, 'Lawn Mowing', 'Garden Area', 'morning'),
(2, 'Flower Arrangement', 'Flower Garden', 'morning'),
(3, 'Equipment Repair', 'Lab Area', 'morning'),
(4, 'Drip System Setup', 'Greenhouse Area', 'morning'),
(5, 'Ground Cleaning', 'Main Gate Area', 'morning'),
(6, 'Perimeter Patrol', 'Boundary Wall Area', 'night'),
(7, 'Tree Planting', 'Tree Plantation Zone', 'morning'),
(8, 'Compost Mixing', 'Compost Area', 'morning'),
(9, 'Pest Spraying', 'Vegetable Garden', 'evening'),
(10, 'Plant Watering', 'Open Lawn', 'morning'),
(11, 'Garden Design', 'Recreation Area', 'morning'),
(12, 'Supply Transport', 'Parking Area', 'morning'),
(13, 'Irrigation Monitoring', 'Sports Complex area', 'morning'),
(14, 'Waste Collection', 'Cafeteria Zone', 'morning'),
(15, 'Pruning', 'Faculty Quarters', 'morning'),
(16, 'Seed Sowing', 'Vegetable Garden', 'morning'),
(17, 'Tool Maintenance', 'Administrative Block area', 'evening'),
(18, 'Fertilizer Application', 'Open Lawn', 'morning'),
(19, 'Area Sweeping', 'Library Complex', 'evening'),
(20, 'Night Security', 'Security Post Area', 'night'),
(21, 'Soil Preparation', 'Garden Area', 'morning'),
(22, 'Organic Waste Processing', 'Compost Area', 'morning'),
(23, 'Insect Control', 'Flower Garden', 'evening'),
(24, 'Greenhouse Monitoring', 'Greenhouse Area', 'morning'),
(25, 'Landscape Maintenance', 'Lotus Point Area', 'morning'),
(26, 'Material Handling', 'CEP Area', 'morning'),
(27, 'Water Quality Check', 'Medical Center', 'morning'),
(28, 'Debris Removal', 'Main Road', 'evening'),
(29, 'Lawn Mowing', 'Sports Complex area', 'morning'),
(30, 'Flower Arrangement', 'Guest House', 'morning'),
(31, 'Equipment Repair', 'Hor-Men (Old) area', 'morning'),
(32, 'Drip System Setup', 'Tree Plantation Zone', 'morning'),
(33, 'Ground Cleaning', 'Lecture Theatre area', 'morning'),
(34, 'Perimeter Patrol', 'Main Gate Area', 'night'),
(35, 'Tree Planting', 'Open Lawn', 'morning'),
(36, 'Compost Mixing', 'Compost Area', 'morning'),
(37, 'Pest Spraying', 'Garden Area', 'evening'),
(38, 'Plant Watering', 'Flower Garden', 'morning'),
(39, 'Garden Design', 'Faculty Quarters', 'morning'),
(40, 'Supply Transport', 'Internal Roads', 'morning'),
(41, 'Irrigation Monitoring', 'Vegetable Garden', 'morning'),
(42, 'Waste Collection', 'Hor-Men (New) Area', 'morning'),
(43, 'Pruning', 'Recreation Area', 'morning'),
(44, 'Seed Sowing', 'Open Lawn', 'morning'),
(45, 'Tool Maintenance', 'Lab Area', 'evening'),
(46, 'Fertilizer Application', 'Tree Plantation Zone', 'morning'),
(47, 'Area Sweeping', 'Parking Area', 'evening'),
(48, 'Night Security', 'Boundary Wall Area', 'night'),
(49, 'Soil Preparation', 'Vegetable Garden', 'morning'),
(50, 'Organic Waste Processing', 'Compost Area', 'morning'),
(51, 'Insect Control', 'Greenhouse Area', 'evening'),
(52, 'Greenhouse Monitoring', 'Greenhouse Area', 'morning'),
(53, 'Landscape Maintenance', 'Garden Area', 'morning'),
(54, 'Material Handling', 'Administrative Block area', 'morning'),
(55, 'Water Quality Check', 'Sports Complex area', 'morning'),
(56, 'Debris Removal', 'Cafeteria Zone', 'evening'),
(57, 'Lawn Mowing', 'Open Lawn', 'morning'),
(58, 'Flower Arrangement', 'Lotus Point Area', 'morning'),
(59, 'Equipment Repair', 'Medical Center', 'morning'),
(60, 'Drip System Setup', 'Flower Garden', 'morning'),
(61, 'Ground Cleaning', 'Hor_women Area', 'morning'),
(62, 'Perimeter Patrol', 'Security Post Area', 'night'),
(63, 'Tree Planting', 'Faculty Quarters', 'morning'),
(64, 'Compost Mixing', 'Compost Area', 'morning'),
(65, 'Pest Spraying', 'Tree Plantation Zone', 'evening'),
(66, 'Plant Watering', 'Recreation Area', 'morning'),
(67, 'Garden Design', 'Guest House', 'morning'),
(68, 'Supply Transport', 'Main Road', 'morning'),
(69, 'Irrigation Monitoring', 'Open Lawn', 'morning'),
(70, 'Waste Collection', 'Library Complex', 'morning'),
(71, 'Pruning', 'Garden Area', 'morning'),
(72, 'Seed Sowing', 'Flower Garden', 'morning'),
(73, 'Tool Maintenance', 'CEP Area', 'evening'),
(74, 'Fertilizer Application', 'Vegetable Garden', 'morning'),
(75, 'Area Sweeping', 'Lecture Theatre area', 'evening'),
(76, 'Night Security', 'Main Gate Area', 'night'),
(77, 'Soil Preparation', 'Tree Plantation Zone', 'morning'),
(78, 'Organic Waste Processing', 'Compost Area', 'morning'),
(79, 'Insect Control', 'Sports Complex area', 'evening'),
(80, 'Greenhouse Monitoring', 'Greenhouse Area', 'morning'),
(81, 'Landscape Maintenance', 'Lotus Point Area', 'morning'),
(82, 'Material Handling', 'Parking Area', 'morning'),
(83, 'Water Quality Check', 'Medical Center', 'morning'),
(84, 'Debris Removal', 'Internal Roads', 'evening'),
(85, 'Lawn Mowing', 'Recreation Area', 'morning'),
(86, 'Flower Arrangement', 'Garden Area', 'morning'),
(87, 'Equipment Repair', 'Administrative Block area', 'morning'),
(88, 'Drip System Setup', 'Open Lawn', 'morning'),
(89, 'Ground Cleaning', 'Faculty Quarters', 'morning'),
(90, 'Perimeter Patrol', 'Boundary Wall Area', 'night'),
(91, 'Tree Planting', 'Garden Area', 'morning'),
(92, 'Compost Mixing', 'Compost Area', 'morning'),
(93, 'Pest Spraying', 'Flower Garden', 'evening'),
(94, 'Plant Watering', 'Vegetable Garden', 'morning'),
(95, 'Garden Design', 'Tree Plantation Zone', 'morning'),
(96, 'Supply Transport', 'Cafeteria Zone', 'morning'),
(97, 'Irrigation Monitoring', 'Greenhouse Area', 'morning'),
(98, 'Waste Collection', 'Hor-Men (Old) area', 'morning'),
(99, 'Pruning', 'Open Lawn', 'morning'),
(100, 'Seed Sowing', 'Recreation Area', 'morning'),
(101, 'Tool Maintenance', 'Lab Area', 'evening'),
(102, 'Fertilizer Application', 'Garden Area', 'morning'),
(103, 'Area Sweeping', 'Guest House', 'evening'),
(104, 'Night Security', 'Security Post Area', 'night'),
(105, 'Soil Preparation', 'Flower Garden', 'morning'),
(106, 'Organic Waste Processing', 'Compost Area', 'morning'),
(107, 'Insect Control', 'Vegetable Garden', 'evening'),
(108, 'Greenhouse Monitoring', 'Greenhouse Area', 'morning'),
(109, 'Landscape Maintenance', 'Sports Complex area', 'morning'),
(110, 'Material Handling', 'Main Road', 'morning'),
(111, 'Water Quality Check', 'Lotus Point Area', 'morning'),
(112, 'Debris Removal', 'Parking Area', 'evening'),
(113, 'Lawn Mowing', 'Faculty Quarters', 'morning'),
(114, 'Flower Arrangement', 'Recreation Area', 'morning'),
(115, 'Equipment Repair', 'Medical Center', 'morning'),
(116, 'Drip System Setup', 'Tree Plantation Zone', 'morning'),
(117, 'Ground Cleaning', 'Library Complex', 'morning'),
(118, 'Perimeter Patrol', 'Main Gate Area', 'night'),
(119, 'Tree Planting', 'Open Lawn', 'morning'),
(120, 'Compost Mixing', 'Compost Area', 'morning'),
(121, 'Pest Spraying', 'Garden Area', 'evening'),
(122, 'Plant Watering', 'Flower Garden', 'morning'),
(123, 'Garden Design', 'Vegetable Garden', 'morning'),
(124, 'Supply Transport', 'Internal Roads', 'morning'),
(125, 'Irrigation Monitoring', 'Recreation Area', 'morning'),
(126, 'Waste Collection', 'CEP Area', 'morning'),
(127, 'Pruning', 'Tree Plantation Zone', 'morning'),
(128, 'Seed Sowing', 'Garden Area', 'morning'),
(129, 'Tool Maintenance', 'Administrative Block area', 'evening'),
(130, 'Fertilizer Application', 'Open Lawn', 'morning'),
(131, 'Area Sweeping', 'Hor-Men (New) Area', 'evening'),
(132, 'Night Security', 'Boundary Wall Area', 'night'),
(133, 'Soil Preparation', 'Sports Complex area', 'morning'),
(134, 'Organic Waste Processing', 'Compost Area', 'morning'),
(135, 'Insect Control', 'Greenhouse Area', 'evening'),
(136, 'Greenhouse Monitoring', 'Greenhouse Area', 'morning'),
(137, 'Landscape Maintenance', 'Faculty Quarters', 'morning'),
(138, 'Material Handling', 'Cafeteria Zone', 'morning'),
(139, 'Water Quality Check', 'Guest House', 'morning'),
(140, 'Debris Removal', 'Lecture Theatre area', 'evening'),
(141, 'Lawn Mowing', 'Lotus Point Area', 'morning'),
(142, 'Flower Arrangement', 'Open Lawn', 'morning'),
(143, 'Equipment Repair', 'Parking Area', 'morning'),
(144, 'Drip System Setup', 'Garden Area', 'morning'),
(145, 'Ground Cleaning', 'Main Road', 'morning'),
(146, 'Perimeter Patrol', 'Security Post Area', 'night'),
(147, 'Tree Planting', 'Tree Plantation Zone', 'morning'),
(148, 'Compost Mixing', 'Compost Area', 'morning'),
(149, 'Pest Spraying', 'Flower Garden', 'evening'),
(150, 'Plant Watering', 'Vegetable Garden', 'morning'),
(151, 'Garden Design', 'Recreation Area', 'morning'),
(152, 'Supply Transport', 'Medical Center', 'morning'),
(153, 'Irrigation Monitoring', 'Open Lawn', 'morning'),
(154, 'Waste Collection', 'Hor_women Area', 'morning'),
(155, 'Pruning', 'Garden Area', 'morning'),
(156, 'Seed Sowing', 'Flower Garden', 'morning'),
(157, 'Tool Maintenance', 'Lab Area', 'evening'),
(158, 'Fertilizer Application', 'Tree Plantation Zone', 'morning'),
(159, 'Area Sweeping', 'Library Complex', 'evening'),
(160, 'Night Security', 'Main Gate Area', 'night'),
(161, 'Soil Preparation', 'Vegetable Garden', 'morning'),
(162, 'Organic Waste Processing', 'Compost Area', 'morning'),
(163, 'Insect Control', 'Sports Complex area', 'evening'),
(164, 'Greenhouse Monitoring', 'Greenhouse Area', 'morning'),
(165, 'Landscape Maintenance', 'Lotus Point Area', 'morning'),
(166, 'Material Handling', 'Administrative Block area', 'morning'),
(167, 'Water Quality Check', 'Faculty Quarters', 'morning'),
(168, 'Debris Removal', 'Internal Roads', 'evening'),
(169, 'Lawn Mowing', 'Recreation Area', 'morning'),
(170, 'Flower Arrangement', 'Guest House', 'morning'),
(171, 'Equipment Repair', 'CEP Area', 'morning'),
(172, 'Drip System Setup', 'Open Lawn', 'morning'),
(173, 'Ground Cleaning', 'Cafeteria Zone', 'morning'),
(174, 'Perimeter Patrol', 'Boundary Wall Area', 'night'),
(175, 'Tree Planting', 'Garden Area', 'morning'),
(176, 'Compost Mixing', 'Compost Area', 'morning'),
(177, 'Pest Spraying', 'Vegetable Garden', 'evening'),
(178, 'Plant Watering', 'Flower Garden', 'morning'),
(179, 'Garden Design', 'Tree Plantation Zone', 'morning'),
(180, 'Supply Transport', 'Parking Area', 'morning'),
(181, 'Irrigation Monitoring', 'Garden Area', 'morning'),
(182, 'Waste Collection', 'Main Road', 'morning'),
(183, 'Pruning', 'Open Lawn', 'morning'),
(184, 'Seed Sowing', 'Recreation Area', 'morning'),
(185, 'Tool Maintenance', 'Medical Center', 'evening'),
(186, 'Fertilizer Application', 'Sports Complex area', 'morning'),
(187, 'Area Sweeping', 'Hor-Men (Old) area', 'evening'),
(188, 'Night Security', 'Security Post Area', 'night'),
(189, 'Soil Preparation', 'Flower Garden', 'morning'),
(190, 'Organic Waste Processing', 'Compost Area', 'morning'),
(191, 'Insect Control', 'Greenhouse Area', 'evening'),
(192, 'Greenhouse Monitoring', 'Greenhouse Area', 'morning'),
(193, 'Landscape Maintenance', 'Faculty Quarters', 'morning'),
(194, 'Material Handling', 'Lotus Point Area', 'morning'),
(195, 'Water Quality Check', 'Library Complex', 'morning'),
(196, 'Debris Removal', 'Lecture Theatre area', 'evening'),
(197, 'Lawn Mowing', 'Garden Area', 'morning'),
(198, 'Flower Arrangement', 'Vegetable Garden', 'morning'),
(199, 'Equipment Repair', 'Guest House', 'morning'),
(200, 'Drip System Setup', 'Tree Plantation Zone', 'morning'),
(201, 'Ground Cleaning', 'Internal Roads', 'morning'),
(202, 'Perimeter Patrol', 'Main Gate Area', 'night'),
(203, 'Tree Planting', 'Open Lawn', 'morning'),
(204, 'Compost Mixing', 'Compost Area', 'morning'),
(205, 'Pest Spraying', 'Garden Area', 'evening'),
(206, 'Plant Watering', 'Flower Garden', 'morning'),
(207, 'Garden Design', 'Recreation Area', 'morning'),
(208, 'Supply Transport', 'Administrative Block area', 'morning'),
(209, 'Irrigation Monitoring', 'Vegetable Garden', 'morning'),
(210, 'Waste Collection', 'Cafeteria Zone', 'morning'),
(211, 'Pruning', 'Tree Plantation Zone', 'morning'),
(212, 'Seed Sowing', 'Open Lawn', 'morning'),
(213, 'Tool Maintenance', 'Lab Area', 'evening'),
(214, 'Fertilizer Application', 'Garden Area', 'morning'),
(215, 'Area Sweeping', 'Hor-Men (New) Area', 'evening'),
(216, 'Night Security', 'Boundary Wall Area', 'night'),
(217, 'Soil Preparation', 'Sports Complex area', 'morning'),
(218, 'Organic Waste Processing', 'Compost Area', 'morning'),
(219, 'Insect Control', 'Flower Garden', 'evening'),
(220, 'Greenhouse Monitoring', 'Greenhouse Area', 'morning'),
(221, 'Landscape Maintenance', 'Faculty Quarters', 'morning'),
(222, 'Material Handling', 'Medical Center', 'morning'),
(223, 'Water Quality Check', 'Parking Area', 'morning'),
(224, 'Debris Removal', 'Main Road', 'evening'),
(225, 'Lawn Mowing', 'Lotus Point Area', 'morning'),
(226, 'Flower Arrangement', 'Recreation Area', 'morning'),
(227, 'Equipment Repair', 'CEP Area', 'morning'),
(228, 'Drip System Setup', 'Vegetable Garden', 'morning'),
(229, 'Ground Cleaning', 'Library Complex', 'morning'),
(230, 'Perimeter Patrol', 'Security Post Area', 'night'),
(231, 'Tree Planting', 'Garden Area', 'morning'),
(232, 'Compost Mixing', 'Compost Area', 'morning'),
(233, 'Pest Spraying', 'Tree Plantation Zone', 'evening'),
(234, 'Plant Watering', 'Open Lawn', 'morning'),
(235, 'Garden Design', 'Flower Garden', 'morning'),
(236, 'Supply Transport', 'Guest House', 'morning'),
(237, 'Irrigation Monitoring', 'Recreation Area', 'morning'),
(238, 'Waste Collection', 'Hor_women Area', 'morning'),
(239, 'Pruning', 'Faculty Quarters', 'morning'),
(240, 'Seed Sowing', 'Garden Area', 'morning'),
(241, 'Tool Maintenance', 'Administrative Block area', 'evening'),
(242, 'Fertilizer Application', 'Vegetable Garden', 'morning'),
(243, 'Area Sweeping', 'Lecture Theatre area', 'evening'),
(244, 'Night Security', 'Main Gate Area', 'night'),
(245, 'Soil Preparation', 'Open Lawn', 'morning'),
(246, 'Organic Waste Processing', 'Compost Area', 'morning'),
(247, 'Insect Control', 'Sports Complex area', 'evening'),
(248, 'Greenhouse Monitoring', 'Greenhouse Area', 'morning'),
(249, 'Landscape Maintenance', 'Tree Plantation Zone', 'morning'),
(250, 'Material Handling', 'Internal Roads', 'morning'),
(251, 'Water Quality Check', 'Cafeteria Zone', 'morning'),
(252, 'Debris Removal', 'Parking Area', 'evening'),
(253, 'Lawn Mowing', 'Garden Area', 'morning'),
(254, 'Flower Arrangement', 'Flower Garden', 'morning'),
(255, 'Equipment Repair', 'Medical Center', 'morning'),
(256, 'Drip System Setup', 'Recreation Area', 'morning'),
(257, 'Ground Cleaning', 'Main Road', 'morning'),
(258, 'Perimeter Patrol', 'Boundary Wall Area', 'night'),
(259, 'Tree Planting', 'Tree Plantation Zone', 'morning'),
(260, 'Compost Mixing', 'Compost Area', 'morning'),
(261, 'Pest Spraying', 'Vegetable Garden', 'evening'),
(262, 'Plant Watering', 'Open Lawn', 'morning'),
(263, 'Garden Design', 'Garden Area', 'morning'),
(264, 'Supply Transport', 'Lotus Point Area', 'morning'),
(265, 'Irrigation Monitoring', 'Flower Garden', 'morning'),
(266, 'Waste Collection', 'Lab Area', 'morning'),
(267, 'Pruning', 'Recreation Area', 'morning'),
(268, 'Seed Sowing', 'Tree Plantation Zone', 'morning'),
(269, 'Tool Maintenance', 'CEP Area', 'evening'),
(270, 'Fertilizer Application', 'Open Lawn', 'morning'),
(271, 'Area Sweeping', 'Guest House', 'evening'),
(272, 'Night Security', 'Security Post Area', 'night'),
(273, 'Soil Preparation', 'Garden Area', 'morning'),
(274, 'Organic Waste Processing', 'Compost Area', 'morning'),
(275, 'Insect Control', 'Greenhouse Area', 'evening'),
(276, 'Greenhouse Monitoring', 'Greenhouse Area', 'morning'),
(277, 'Landscape Maintenance', 'Faculty Quarters', 'morning'),
(278, 'Material Handling', 'Administrative Block area', 'morning'),
(279, 'Water Quality Check', 'Sports Complex area', 'morning'),
(280, 'Debris Removal', 'Library Complex', 'evening'),
(281, 'Lawn Mowing', 'Open Lawn', 'morning'),
(282, 'Flower Arrangement', 'Vegetable Garden', 'morning'),
(283, 'Equipment Repair', 'Hor-Men (Old) area', 'morning'),
(284, 'Drip System Setup', 'Garden Area', 'morning'),
(285, 'Ground Cleaning', 'Cafeteria Zone', 'morning'),
(286, 'Perimeter Patrol', 'Main Gate Area', 'night'),
(287, 'Tree Planting', 'Tree Plantation Zone', 'morning'),
(288, 'Compost Mixing', 'Compost Area', 'morning'),
(289, 'Pest Spraying', 'Flower Garden', 'evening'),
(290, 'Plant Watering', 'Recreation Area', 'morning'),
(291, 'Garden Design', 'Open Lawn', 'morning'),
(292, 'Supply Transport', 'Internal Roads', 'morning'),
(293, 'Irrigation Monitoring', 'Vegetable Garden', 'morning'),
(294, 'Waste Collection', 'Parking Area', 'morning'),
(295, 'Pruning', 'Garden Area', 'morning'),
(296, 'Seed Sowing', 'Flower Garden', 'morning'),
(297, 'Tool Maintenance', 'Medical Center', 'evening'),
(298, 'Fertilizer Application', 'Tree Plantation Zone', 'morning'),
(299, 'Area Sweeping', 'Hor-Men (New) Area', 'evening'),
(300, 'Night Security', 'Boundary Wall Area', 'night'),
(301, 'Soil Preparation', 'Sports Complex area', 'morning'),
(302, 'Organic Waste Processing', 'Compost Area', 'morning'),
(303, 'Insect Control', 'Garden Area', 'evening'),
(304, 'Greenhouse Monitoring', 'Greenhouse Area', 'morning'),
(305, 'Landscape Maintenance', 'Lotus Point Area', 'morning'),
(306, 'Material Handling', 'Main Road', 'morning'),
(307, 'Water Quality Check', 'Faculty Quarters', 'morning'),
(308, 'Debris Removal', 'Lecture Theatre area', 'evening'),
(309, 'Lawn Mowing', 'Recreation Area', 'morning'),
(310, 'Flower Arrangement', 'Open Lawn', 'morning'),
(311, 'Equipment Repair', 'Lab Area', 'morning'),
(312, 'Drip System Setup', 'Vegetable Garden', 'morning'),
(313, 'Ground Cleaning', 'Guest House', 'morning'),
(314, 'Perimeter Patrol', 'Security Post Area', 'night'),
(315, 'Tree Planting', 'Garden Area', 'morning'),
(316, 'Compost Mixing', 'Compost Area', 'morning'),
(317, 'Pest Spraying', 'Tree Plantation Zone', 'evening'),
(318, 'Plant Watering', 'Flower Garden', 'morning'),
(319, 'Garden Design', 'Recreation Area', 'morning'),
(320, 'Supply Transport', 'Administrative Block area', 'morning'),
(321, 'Irrigation Monitoring', 'Open Lawn', 'morning'),
(322, 'Waste Collection', 'CEP Area', 'morning'),
(323, 'Pruning', 'Tree Plantation Zone', 'morning'),
(324, 'Seed Sowing', 'Garden Area', 'morning'),
(325, 'Tool Maintenance', 'Parking Area', 'evening'),
(326, 'Fertilizer Application', 'Vegetable Garden', 'morning'),
(327, 'Area Sweeping', 'Library Complex', 'evening'),
(328, 'Night Security', 'Main Gate Area', 'night'),
(329, 'Soil Preparation', 'Flower Garden', 'morning'),
(330, 'Organic Waste Processing', 'Compost Area', 'morning'),
(331, 'Insect Control', 'Sports Complex area', 'evening'),
(332, 'Greenhouse Monitoring', 'Greenhouse Area', 'morning'),
(333, 'Landscape Maintenance', 'Faculty Quarters', 'morning'),
(334, 'Material Handling', 'Cafeteria Zone', 'morning'),
(335, 'Water Quality Check', 'Medical Center', 'morning'),
(336, 'Debris Removal', 'Internal Roads', 'evening'),
(337, 'Lawn Mowing', 'Garden Area', 'morning'),
(338, 'Flower Arrangement', 'Lotus Point Area', 'morning'),
(339, 'Equipment Repair', 'Hor_women Area', 'morning'),
(340, 'Drip System Setup', 'Open Lawn', 'morning'),
(341, 'Ground Cleaning', 'Main Road', 'morning'),
(342, 'Perimeter Patrol', 'Boundary Wall Area', 'night'),
(343, 'Tree Planting', 'Tree Plantation Zone', 'morning'),
(344, 'Compost Mixing', 'Compost Area', 'morning'),
(345, 'Pest Spraying', 'Vegetable Garden', 'evening'),
(346, 'Plant Watering', 'Recreation Area', 'morning'),
(347, 'Garden Design', 'Flower Garden', 'morning'),
(348, 'Supply Transport', 'Guest House', 'morning'),
(349, 'Irrigation Monitoring', 'Garden Area', 'morning'),
(350, 'Waste Collection', 'Lecture Theatre area', 'morning'),
(351, 'Pruning', 'Open Lawn', 'morning'),
(352, 'Seed Sowing', 'Tree Plantation Zone', 'morning'),
(353, 'Tool Maintenance', 'Administrative Block area', 'evening'),
(354, 'Fertilizer Application', 'Sports Complex area', 'morning'),
(355, 'Area Sweeping', 'Hor-Men (Old) area', 'evening'),
(356, 'Night Security', 'Security Post Area', 'night'),
(357, 'Soil Preparation', 'Vegetable Garden', 'morning'),
(358, 'Organic Waste Processing', 'Compost Area', 'morning'),
(359, 'Insect Control', 'Greenhouse Area', 'evening'),
(360, 'Greenhouse Monitoring', 'Greenhouse Area', 'morning'),
(361, 'Landscape Maintenance', 'Garden Area', 'morning'),
(362, 'Material Handling', 'Parking Area', 'morning'),
(363, 'Water Quality Check', 'Faculty Quarters', 'morning'),
(364, 'Debris Removal', 'CEP Area', 'evening'),
(365, 'Lawn Mowing', 'Recreation Area', 'morning'),
(366, 'Flower Arrangement', 'Flower Garden', 'morning'),
(367, 'Equipment Repair', 'Medical Center', 'morning'),
(368, 'Drip System Setup', 'Garden Area', 'morning'),
(369, 'Ground Cleaning', 'Library Complex', 'morning'),
(370, 'Perimeter Patrol', 'Main Gate Area', 'night'),
(371, 'Tree Planting', 'Open Lawn', 'morning'),
(372, 'Compost Mixing', 'Compost Area', 'morning'),
(373, 'Pest Spraying', 'Tree Plantation Zone', 'evening'),
(374, 'Plant Watering', 'Vegetable Garden', 'morning'),
(375, 'Garden Design', 'Recreation Area', 'morning'),
(376, 'Supply Transport', 'Internal Roads', 'morning'),
(377, 'Irrigation Monitoring', 'Flower Garden', 'morning'),
(378, 'Waste Collection', 'Main Road', 'morning'),
(379, 'Pruning', 'Garden Area', 'morning'),
(380, 'Seed Sowing', 'Open Lawn', 'morning'),
(381, 'Tool Maintenance', 'Lab Area', 'evening'),
(382, 'Fertilizer Application', 'Tree Plantation Zone', 'morning'),
(383, 'Area Sweeping', 'Cafeteria Zone', 'evening'),
(384, 'Night Security', 'Boundary Wall Area', 'night'),
(385, 'Soil Preparation', 'Sports Complex area', 'morning'),
(386, 'Organic Waste Processing', 'Compost Area', 'morning'),
(387, 'Insect Control', 'Garden Area', 'evening'),
(388, 'Greenhouse Monitoring', 'Greenhouse Area', 'morning'),
(389, 'Landscape Maintenance', 'Lotus Point Area', 'morning'),
(390, 'Material Handling', 'Guest House', 'morning'),
(391, 'Water Quality Check', 'Administrative Block area', 'morning'),
(392, 'Debris Removal', 'Parking Area', 'evening'),
(393, 'Lawn Mowing', 'Garden Area', 'morning'),
(394, 'Flower Arrangement', 'Vegetable Garden', 'morning'),
(395, 'Equipment Repair', 'Hor-Men (New) Area', 'morning'),
(396, 'Drip System Setup', 'Recreation Area', 'morning'),
(397, 'Ground Cleaning', 'Faculty Quarters', 'morning'),
(398, 'Perimeter Patrol', 'Security Post Area', 'night'),
(399, 'Tree Planting', 'Tree Plantation Zone', 'morning'),
(400, 'Compost Mixing', 'Compost Area', 'morning'),
(1, 'Pest Spraying', 'Flower Garden', 'evening'),
(2, 'Plant Watering', 'Open Lawn', 'morning'),
(3, 'Garden Design', 'Recreation Area', 'morning'),
(4, 'Supply Transport', 'Medical Center', 'morning'),
(5, 'Irrigation Monitoring', 'Vegetable Garden', 'morning'),
(6, 'Waste Collection', 'Lecture Theatre area', 'morning'),
(7, 'Pruning', 'Garden Area', 'morning'),
(8, 'Seed Sowing', 'Flower Garden', 'morning'),
(9, 'Tool Maintenance', 'CEP Area', 'evening'),
(10, 'Fertilizer Application', 'Open Lawn', 'morning'),
(11, 'Area Sweeping', 'Hor_women Area', 'evening'),
(12, 'Night Security', 'Main Gate Area', 'night'),
(13, 'Soil Preparation', 'Tree Plantation Zone', 'morning'),
(14, 'Organic Waste Processing', 'Compost Area', 'morning'),
(15, 'Insect Control', 'Sports Complex area', 'evening'),
(16, 'Greenhouse Monitoring', 'Greenhouse Area', 'morning'),
(17, 'Landscape Maintenance', 'Faculty Quarters', 'morning'),
(18, 'Material Handling', 'Library Complex', 'morning'),
(19, 'Water Quality Check', 'Garden Area', 'morning'),
(20, 'Debris Removal', 'Internal Roads', 'evening'),
(21, 'Lawn Mowing', 'Lotus Point Area', 'morning'),
(22, 'Flower Arrangement', 'Recreation Area', 'morning'),
(23, 'Equipment Repair', 'Guest House', 'morning'),
(24, 'Drip System Setup', 'Vegetable Garden', 'morning'),
(25, 'Ground Cleaning', 'Parking Area', 'morning'),
(26, 'Perimeter Patrol', 'Boundary Wall Area', 'night'),
(27, 'Tree Planting', 'Open Lawn', 'morning'),
(28, 'Compost Mixing', 'Compost Area', 'morning'),
(29, 'Pest Spraying', 'Garden Area', 'evening'),
(30, 'Plant Watering', 'Tree Plantation Zone', 'morning'),
(31, 'Garden Design', 'Flower Garden', 'morning'),
(32, 'Supply Transport', 'Main Road', 'morning'),
(33, 'Irrigation Monitoring', 'Recreation Area', 'morning'),
(34, 'Waste Collection', 'Administrative Block area', 'morning'),
(35, 'Pruning', 'Sports Complex area', 'morning'),
(36, 'Seed Sowing', 'Open Lawn', 'morning'),
(37, 'Tool Maintenance', 'Medical Center', 'evening'),
(38, 'Fertilizer Application', 'Garden Area', 'morning'),
(39, 'Area Sweeping', 'Lab Area', 'evening'),
(40, 'Night Security', 'Security Post Area', 'night'),
(41, 'Soil Preparation', 'Flower Garden', 'morning'),
(42, 'Organic Waste Processing', 'Compost Area', 'morning'),
(43, 'Insect Control', 'Vegetable Garden', 'evening'),
(44, 'Greenhouse Monitoring', 'Greenhouse Area', 'morning'),
(45, 'Landscape Maintenance', 'Tree Plantation Zone', 'morning'),
(46, 'Material Handling', 'Cafeteria Zone', 'morning'),
(47, 'Water Quality Check', 'Faculty Quarters', 'morning'),
(48, 'Debris Removal', 'CEP Area', 'evening'),
(49, 'Lawn Mowing', 'Recreation Area', 'morning'),
(50, 'Flower Arrangement', 'Garden Area', 'morning'),
(51, 'Equipment Repair', 'Hor-Men (Old) area', 'morning'),
(52, 'Drip System Setup', 'Open Lawn', 'morning'),
(53, 'Ground Cleaning', 'Library Complex', 'morning'),
(54, 'Perimeter Patrol', 'Main Gate Area', 'night'),
(55, 'Tree Planting', 'Tree Plantation Zone', 'morning'),
(56, 'Compost Mixing', 'Compost Area', 'morning'),
(57, 'Pest Spraying', 'Sports Complex area', 'evening'),
(58, 'Plant Watering', 'Flower Garden', 'morning'),
(59, 'Garden Design', 'Vegetable Garden', 'morning'),
(60, 'Supply Transport', 'Guest House', 'morning'),
(61, 'Irrigation Monitoring', 'Garden Area', 'morning'),
(62, 'Waste Collection', 'Parking Area', 'morning'),
(63, 'Pruning', 'Recreation Area', 'morning'),
(64, 'Seed Sowing', 'Tree Plantation Zone', 'morning'),
(65, 'Tool Maintenance', 'Administrative Block area', 'evening'),
(66, 'Fertilizer Application', 'Open Lawn', 'morning'),
(67, 'Area Sweeping', 'Internal Roads', 'evening'),
(68, 'Night Security', 'Boundary Wall Area', 'night'),
(69, 'Soil Preparation', 'Garden Area', 'morning'),
(70, 'Organic Waste Processing', 'Compost Area', 'morning'),
(71, 'Insect Control', 'Greenhouse Area', 'evening'),
(72, 'Greenhouse Monitoring', 'Greenhouse Area', 'morning'),
(73, 'Landscape Maintenance', 'Lotus Point Area', 'morning'),
(74, 'Material Handling', 'Medical Center', 'morning'),
(75, 'Water Quality Check', 'Sports Complex area', 'morning'),
(76, 'Debris Removal', 'Lecture Theatre area', 'evening'),
(77, 'Lawn Mowing', 'Faculty Quarters', 'morning'),
(78, 'Flower Arrangement', 'Open Lawn', 'morning'),
(79, 'Equipment Repair', 'Hor-Men (New) Area', 'morning'),
(80, 'Drip System Setup', 'Recreation Area', 'morning'),
(81, 'Ground Cleaning', 'Main Road', 'morning'),
(82, 'Perimeter Patrol', 'Security Post Area', 'night'),
(83, 'Tree Planting', 'Garden Area', 'morning'),
(84, 'Compost Mixing', 'Compost Area', 'morning'),
(85, 'Pest Spraying', 'Flower Garden', 'evening'),
(86, 'Plant Watering', 'Vegetable Garden', 'morning'),
(87, 'Garden Design', 'Tree Plantation Zone', 'morning'),
(88, 'Supply Transport', 'Cafeteria Zone', 'morning'),
(89, 'Irrigation Monitoring', 'Open Lawn', 'morning'),
(90, 'Waste Collection', 'Hor_women Area', 'morning'),
(91, 'Pruning', 'Garden Area', 'morning'),
(92, 'Seed Sowing', 'Flower Garden', 'morning'),
(93, 'Tool Maintenance', 'Lab Area', 'evening'),
(94, 'Fertilizer Application', 'Recreation Area', 'morning'),
(95, 'Area Sweeping', 'Guest House', 'evening'),
(96, 'Night Security', 'Main Gate Area', 'night'),
(97, 'Soil Preparation', 'Tree Plantation Zone', 'morning'),
(98, 'Organic Waste Processing', 'Compost Area', 'morning'),
(99, 'Insect Control', 'Sports Complex area', 'evening'),
(100, 'Greenhouse Monitoring', 'Greenhouse Area', 'morning'),
(101, 'Landscape Maintenance', 'Faculty Quarters', 'morning'),
(102, 'Material Handling', 'Library Complex', 'morning'),
(103, 'Water Quality Check', 'Garden Area', 'morning'),
(104, 'Debris Removal', 'Parking Area', 'evening'),
(105, 'Lawn Mowing', 'Open Lawn', 'morning'),
(106, 'Flower Arrangement', 'Vegetable Garden', 'morning'),
(107, 'Equipment Repair', 'CEP Area', 'morning'),
(108, 'Drip System Setup', 'Garden Area', 'morning'),
(109, 'Ground Cleaning', 'Administrative Block area', 'morning'),
(110, 'Perimeter Patrol', 'Boundary Wall Area', 'night'),
(111, 'Tree Planting', 'Tree Plantation Zone', 'morning'),
(112, 'Compost Mixing', 'Compost Area', 'morning'),
(113, 'Pest Spraying', 'Greenhouse Area', 'evening'),
(114, 'Plant Watering', 'Flower Garden', 'morning'),
(115, 'Garden Design', 'Recreation Area', 'morning'),
(116, 'Supply Transport', 'Internal Roads', 'morning'),
(117, 'Irrigation Monitoring', 'Vegetable Garden', 'morning'),
(118, 'Waste Collection', 'Medical Center', 'morning'),
(119, 'Pruning', 'Open Lawn', 'morning'),
(120, 'Seed Sowing', 'Garden Area', 'morning'),
(121, 'Tool Maintenance', 'Lotus Point Area', 'evening'),
(122, 'Fertilizer Application', 'Tree Plantation Zone', 'morning'),
(123, 'Area Sweeping', 'Sports Complex area', 'evening'),
(124, 'Night Security', 'Security Post Area', 'night'),
(125, 'Soil Preparation', 'Flower Garden', 'morning'),
(126, 'Organic Waste Processing', 'Compost Area', 'morning'),
(127, 'Insect Control', 'Garden Area', 'evening'),
(128, 'Greenhouse Monitoring', 'Greenhouse Area', 'morning'),
(129, 'Landscape Maintenance', 'Recreation Area', 'morning'),
(130, 'Material Handling', 'Main Road', 'morning'),
(131, 'Water Quality Check', 'Faculty Quarters', 'morning'),
(132, 'Debris Removal', 'Lecture Theatre area', 'evening'),
(133, 'Lawn Mowing', 'Garden Area', 'morning'),
(134, 'Flower Arrangement', 'Open Lawn', 'morning'),
(135, 'Equipment Repair', 'Guest House', 'morning'),
(136, 'Drip System Setup', 'Vegetable Garden', 'morning'),
(137, 'Ground Cleaning', 'Cafeteria Zone', 'morning'),
(138, 'Perimeter Patrol', 'Main Gate Area', 'night'),
(139, 'Tree Planting', 'Tree Plantation Zone', 'morning'),
(140, 'Compost Mixing', 'Compost Area', 'morning'),
(141, 'Pest Spraying', 'Sports Complex area', 'evening'),
(142, 'Plant Watering', 'Flower Garden', 'morning'),
(143, 'Garden Design', 'Garden Area', 'morning'),
(144, 'Supply Transport', 'Parking Area', 'morning'),
(145, 'Irrigation Monitoring', 'Recreation Area', 'morning'),
(146, 'Waste Collection', 'Hor-Men (Old) area', 'morning'),
(147, 'Pruning', 'Open Lawn', 'morning'),
(148, 'Seed Sowing', 'Tree Plantation Zone', 'morning'),
(149, 'Tool Maintenance', 'Administrative Block area', 'evening'),
(150, 'Fertilizer Application', 'Garden Area', 'morning'),
(151, 'Area Sweeping', 'Library Complex', 'evening'),
(152, 'Night Security', 'Boundary Wall Area', 'night'),
(153, 'Soil Preparation', 'Vegetable Garden', 'morning'),
(154, 'Organic Waste Processing', 'Compost Area', 'morning'),
(155, 'Insect Control', 'Flower Garden', 'evening'),
(156, 'Greenhouse Monitoring', 'Greenhouse Area', 'morning'),
(157, 'Landscape Maintenance', 'Faculty Quarters', 'morning'),
(158, 'Material Handling', 'CEP Area', 'morning'),
(159, 'Water Quality Check', 'Medical Center', 'morning'),
(160, 'Debris Removal', 'Internal Roads', 'evening'),
(161, 'Lawn Mowing', 'Recreation Area', 'morning'),
(162, 'Flower Arrangement', 'Garden Area', 'morning'),
(163, 'Equipment Repair', 'Hor-Men (New) Area', 'morning'),
(164, 'Drip System Setup', 'Open Lawn', 'morning'),
(165, 'Ground Cleaning', 'Lotus Point Area', 'morning'),
(166, 'Perimeter Patrol', 'Security Post Area', 'night'),
(167, 'Tree Planting', 'Tree Plantation Zone', 'morning'),
(168, 'Compost Mixing', 'Compost Area', 'morning'),
(169, 'Pest Spraying', 'Vegetable Garden', 'evening'),
(170, 'Plant Watering', 'Flower Garden', 'morning'),
(171, 'Garden Design', 'Recreation Area', 'morning'),
(172, 'Supply Transport', 'Main Road', 'morning'),
(173, 'Irrigation Monitoring', 'Garden Area', 'morning'),
(174, 'Waste Collection', 'Sports Complex area', 'morning'),
(175, 'Pruning', 'Open Lawn', 'morning'),
(176, 'Seed Sowing', 'Tree Plantation Zone', 'morning'),
(177, 'Tool Maintenance', 'Lab Area', 'evening'),
(178, 'Fertilizer Application', 'Garden Area', 'morning'),
(179, 'Area Sweeping', 'Hor_women Area', 'evening'),
(180, 'Night Security', 'Main Gate Area', 'night'),
(181, 'Soil Preparation', 'Flower Garden', 'morning'),
(182, 'Organic Waste Processing', 'Compost Area', 'morning'),
(183, 'Insect Control', 'Greenhouse Area', 'evening'),
(184, 'Greenhouse Monitoring', 'Greenhouse Area', 'morning'),
(185, 'Landscape Maintenance', 'Faculty Quarters', 'morning'),
(186, 'Material Handling', 'Guest House', 'morning'),
(187, 'Water Quality Check', 'Recreation Area', 'morning'),
(188, 'Debris Removal', 'Parking Area', 'evening'),
(189, 'Lawn Mowing', 'Garden Area', 'morning'),
(190, 'Flower Arrangement', 'Vegetable Garden', 'morning'),
(191, 'Equipment Repair', 'Administrative Block area', 'morning'),
(192, 'Drip System Setup', 'Open Lawn', 'morning'),
(193, 'Ground Cleaning', 'Cafeteria Zone', 'morning'),
(194, 'Perimeter Patrol', 'Boundary Wall Area', 'night'),
(195, 'Tree Planting', 'Tree Plantation Zone', 'morning'),
(196, 'Compost Mixing', 'Compost Area', 'morning'),
(197, 'Pest Spraying', 'Sports Complex area', 'evening'),
(198, 'Plant Watering', 'Flower Garden', 'morning'),
(199, 'Garden Design', 'Garden Area', 'morning'),
(200, 'Supply Transport', 'Medical Center', 'morning'),
(201, 'Irrigation Monitoring', 'Recreation Area', 'morning'),
(202, 'Waste Collection', 'Library Complex', 'morning'),
(203, 'Pruning', 'Open Lawn', 'morning'),
(204, 'Seed Sowing', 'Tree Plantation Zone', 'morning'),
(205, 'Tool Maintenance', 'CEP Area', 'evening'),
(206, 'Fertilizer Application', 'Garden Area', 'morning'),
(207, 'Area Sweeping', 'Lecture Theatre area', 'evening'),
(208, 'Night Security', 'Security Post Area', 'night'),
(209, 'Soil Preparation', 'Vegetable Garden', 'morning'),
(210, 'Organic Waste Processing', 'Compost Area', 'morning'),
(211, 'Insect Control', 'Flower Garden', 'evening'),
(212, 'Greenhouse Monitoring', 'Greenhouse Area', 'morning'),
(213, 'Landscape Maintenance', 'Faculty Quarters', 'morning'),
(214, 'Material Handling', 'Internal Roads', 'morning'),
(215, 'Water Quality Check', 'Garden Area', 'morning'),
(216, 'Debris Removal', 'Main Road', 'evening'),
(217, 'Lawn Mowing', 'Open Lawn', 'morning'),
(218, 'Flower Arrangement', 'Recreation Area', 'morning'),
(219, 'Equipment Repair', 'Lotus Point Area', 'morning'),
(220, 'Drip System Setup', 'Garden Area', 'morning'),
(221, 'Ground Cleaning', 'Parking Area', 'morning'),
(222, 'Perimeter Patrol', 'Main Gate Area', 'night'),
(223, 'Tree Planting', 'Tree Plantation Zone', 'morning'),
(224, 'Compost Mixing', 'Compost Area', 'morning'),
(225, 'Pest Spraying', 'Greenhouse Area', 'evening'),
(226, 'Plant Watering', 'Flower Garden', 'morning'),
(227, 'Garden Design', 'Vegetable Garden', 'morning'),
(228, 'Supply Transport', 'Guest House', 'morning'),
(229, 'Irrigation Monitoring', 'Open Lawn', 'morning'),
(230, 'Waste Collection', 'Hor-Men (Old) area', 'morning'),
(231, 'Pruning', 'Garden Area', 'morning'),
(232, 'Seed Sowing', 'Tree Plantation Zone', 'morning'),
(233, 'Tool Maintenance', 'Administrative Block area', 'evening'),
(234, 'Fertilizer Application', 'Recreation Area', 'morning'),
(235, 'Area Sweeping', 'Sports Complex area', 'evening'),
(236, 'Night Security', 'Boundary Wall Area', 'night'),
(237, 'Soil Preparation', 'Flower Garden', 'morning'),
(238, 'Organic Waste Processing', 'Compost Area', 'morning'),
(239, 'Insect Control', 'Garden Area', 'evening'),
(240, 'Greenhouse Monitoring', 'Greenhouse Area', 'morning'),
(241, 'Landscape Maintenance', 'Faculty Quarters', 'morning'),
(242, 'Material Handling', 'Medical Center', 'morning'),
(243, 'Water Quality Check', 'Cafeteria Zone', 'morning'),
(244, 'Debris Removal', 'Library Complex', 'evening'),
(245, 'Lawn Mowing', 'Recreation Area', 'morning'),
(246, 'Flower Arrangement', 'Open Lawn', 'morning'),
(247, 'Equipment Repair', 'Hor-Men (New) Area', 'morning'),
(248, 'Drip System Setup', 'Vegetable Garden', 'morning'),
(249, 'Ground Cleaning', 'Main Road', 'morning'),
(250, 'Perimeter Patrol', 'Security Post Area', 'night'),
(251, 'Tree Planting', 'Tree Plantation Zone', 'morning'),
(252, 'Compost Mixing', 'Compost Area', 'morning'),
(253, 'Pest Spraying', 'Sports Complex area', 'evening'),
(254, 'Plant Watering', 'Flower Garden', 'morning'),
(255, 'Garden Design', 'Garden Area', 'morning'),
(256, 'Supply Transport', 'Parking Area', 'morning'),
(257, 'Irrigation Monitoring', 'Recreation Area', 'morning'),
(258, 'Waste Collection', 'CEP Area', 'morning'),
(259, 'Pruning', 'Open Lawn', 'morning'),
(260, 'Seed Sowing', 'Tree Plantation Zone', 'morning'),
(261, 'Tool Maintenance', 'Lab Area', 'evening'),
(262, 'Fertilizer Application', 'Garden Area', 'morning'),
(263, 'Area Sweeping', 'Hor_women Area', 'evening'),
(264, 'Night Security', 'Main Gate Area', 'night'),
(265, 'Soil Preparation', 'Vegetable Garden', 'morning'),
(266, 'Organic Waste Processing', 'Compost Area', 'morning'),
(267, 'Insect Control', 'Greenhouse Area', 'evening'),
(268, 'Greenhouse Monitoring', 'Greenhouse Area', 'morning'),
(269, 'Landscape Maintenance', 'Faculty Quarters', 'morning'),
(270, 'Material Handling', 'Internal Roads', 'morning'),
(271, 'Water Quality Check', 'Lotus Point Area', 'morning'),
(272, 'Debris Removal', 'Guest House', 'evening'),
(273, 'Lawn Mowing', 'Garden Area', 'morning'),
(274, 'Flower Arrangement', 'Flower Garden', 'morning'),
(275, 'Equipment Repair', 'Administrative Block area', 'morning'),
(276, 'Drip System Setup', 'Open Lawn', 'morning'),
(277, 'Ground Cleaning', 'Medical Center', 'morning'),
(278, 'Perimeter Patrol', 'Boundary Wall Area', 'night'),
(279, 'Tree Planting', 'Tree Plantation Zone', 'morning'),
(280, 'Compost Mixing', 'Compost Area', 'morning'),
(281, 'Pest Spraying', 'Vegetable Garden', 'evening'),
(282, 'Plant Watering', 'Recreation Area', 'morning'),
(283, 'Garden Design', 'Open Lawn', 'morning'),
(284, 'Supply Transport', 'Cafeteria Zone', 'morning'),
(285, 'Irrigation Monitoring', 'Garden Area', 'morning'),
(286, 'Waste Collection', 'Sports Complex area', 'morning'),
(287, 'Pruning', 'Tree Plantation Zone', 'morning'),
(288, 'Seed Sowing', 'Flower Garden', 'morning'),
(289, 'Tool Maintenance', 'Lecture Theatre area', 'evening'),
(290, 'Fertilizer Application', 'Recreation Area', 'morning'),
(291, 'Area Sweeping', 'Library Complex', 'evening'),
(292, 'Night Security', 'Security Post Area', 'night'),
(293, 'Soil Preparation', 'Garden Area', 'morning'),
(294, 'Organic Waste Processing', 'Compost Area', 'morning'),
(295, 'Insect Control', 'Flower Garden', 'evening'),
(296, 'Greenhouse Monitoring', 'Greenhouse Area', 'morning'),
(297, 'Landscape Maintenance', 'Faculty Quarters', 'morning'),
(298, 'Material Handling', 'Main Road', 'morning'),
(299, 'Water Quality Check', 'Recreation Area', 'morning'),
(300, 'Debris Removal', 'Parking Area', 'evening'),
(301, 'Lawn Mowing', 'Open Lawn', 'morning'),
(302, 'Flower Arrangement', 'Vegetable Garden', 'morning'),
(303, 'Equipment Repair', 'Hor-Men (Old) area', 'morning'),
(304, 'Drip System Setup', 'Garden Area', 'morning'),
(305, 'Ground Cleaning', 'Guest House', 'morning'),
(306, 'Perimeter Patrol', 'Main Gate Area', 'night'),
(307, 'Tree Planting', 'Tree Plantation Zone', 'morning'),
(308, 'Compost Mixing', 'Compost Area', 'morning'),
(309, 'Pest Spraying', 'Sports Complex area', 'evening'),
(310, 'Plant Watering', 'Flower Garden', 'morning'),
(311, 'Garden Design', 'Garden Area', 'morning'),
(312, 'Supply Transport', 'CEP Area', 'morning'),
(313, 'Irrigation Monitoring', 'Vegetable Garden', 'morning'),
(314, 'Waste Collection', 'Internal Roads', 'morning'),
(315, 'Pruning', 'Open Lawn', 'morning'),
(316, 'Seed Sowing', 'Tree Plantation Zone', 'morning'),
(317, 'Tool Maintenance', 'Administrative Block area', 'evening'),
(318, 'Fertilizer Application', 'Recreation Area', 'morning'),
(319, 'Area Sweeping', 'Medical Center', 'evening'),
(320, 'Night Security', 'Boundary Wall Area', 'night'),
(321, 'Soil Preparation', 'Flower Garden', 'morning'),
(322, 'Organic Waste Processing', 'Compost Area', 'morning'),
(323, 'Insect Control', 'Greenhouse Area', 'evening'),
(324, 'Greenhouse Monitoring', 'Greenhouse Area', 'morning'),
(325, 'Landscape Maintenance', 'Faculty Quarters', 'morning'),
(326, 'Material Handling', 'Lotus Point Area', 'morning'),
(327, 'Water Quality Check', 'Garden Area', 'morning'),
(328, 'Debris Removal', 'Cafeteria Zone', 'evening'),
(329, 'Lawn Mowing', 'Recreation Area', 'morning'),
(330, 'Flower Arrangement', 'Open Lawn', 'morning'),
(331, 'Equipment Repair', 'Lab Area', 'morning'),
(332, 'Drip System Setup', 'Vegetable Garden', 'morning'),
(333, 'Ground Cleaning', 'Sports Complex area', 'morning'),
(334, 'Perimeter Patrol', 'Security Post Area', 'night'),
(335, 'Tree Planting', 'Tree Plantation Zone', 'morning'),
(336, 'Compost Mixing', 'Compost Area', 'morning'),
(337, 'Pest Spraying', 'Garden Area', 'evening'),
(338, 'Plant Watering', 'Flower Garden', 'morning'),
(339, 'Garden Design', 'Recreation Area', 'morning'),
(340, 'Supply Transport', 'Library Complex', 'morning'),
(341, 'Irrigation Monitoring', 'Open Lawn', 'morning'),
(342, 'Waste Collection', 'Hor-Men (New) Area', 'morning'),
(343, 'Pruning', 'Tree Plantation Zone', 'morning'),
(344, 'Seed Sowing', 'Garden Area', 'morning'),
(345, 'Tool Maintenance', 'Parking Area', 'evening'),
(346, 'Fertilizer Application', 'Vegetable Garden', 'morning'),
(347, 'Area Sweeping', 'Guest House', 'evening'),
(348, 'Night Security', 'Main Gate Area', 'night'),
(349, 'Soil Preparation', 'Flower Garden', 'morning'),
(350, 'Organic Waste Processing', 'Compost Area', 'morning'),
(351, 'Insect Control', 'Sports Complex area', 'evening'),
(352, 'Greenhouse Monitoring', 'Greenhouse Area', 'morning'),
(353, 'Landscape Maintenance', 'Faculty Quarters', 'morning'),
(354, 'Material Handling', 'Main Road', 'morning'),
(355, 'Water Quality Check', 'Recreation Area', 'morning'),
(356, 'Debris Removal', 'Internal Roads', 'evening'),
(357, 'Lawn Mowing', 'Garden Area', 'morning'),
(358, 'Flower Arrangement', 'Open Lawn', 'morning'),
(359, 'Equipment Repair', 'Hor_women Area', 'morning'),
(360, 'Drip System Setup', 'Tree Plantation Zone', 'morning'),
(361, 'Ground Cleaning', 'Medical Center', 'morning'),
(362, 'Perimeter Patrol', 'Boundary Wall Area', 'night'),
(363, 'Tree Planting', 'Garden Area', 'morning'),
(364, 'Compost Mixing', 'Compost Area', 'morning'),
(365, 'Pest Spraying', 'Vegetable Garden', 'evening'),
(366, 'Plant Watering', 'Flower Garden', 'morning'),
(367, 'Garden Design', 'Recreation Area', 'morning'),
(368, 'Supply Transport', 'Administrative Block area', 'morning'),
(369, 'Irrigation Monitoring', 'Open Lawn', 'morning'),
(370, 'Waste Collection', 'CEP Area', 'morning'),
(371, 'Pruning', 'Tree Plantation Zone', 'morning'),
(372, 'Seed Sowing', 'Garden Area', 'morning'),
(373, 'Tool Maintenance', 'Lotus Point Area', 'evening'),
(374, 'Fertilizer Application', 'Recreation Area', 'morning'),
(375, 'Area Sweeping', 'Cafeteria Zone', 'evening'),
(376, 'Night Security', 'Security Post Area', 'night'),
(377, 'Soil Preparation', 'Flower Garden', 'morning'),
(378, 'Organic Waste Processing', 'Compost Area', 'morning'),
(379, 'Insect Control', 'Greenhouse Area', 'evening'),
(380, 'Greenhouse Monitoring', 'Greenhouse Area', 'morning'),
(381, 'Landscape Maintenance', 'Faculty Quarters', 'morning'),
(382, 'Material Handling', 'Sports Complex area', 'morning'),
(383, 'Water Quality Check', 'Garden Area', 'morning'),
(384, 'Debris Removal', 'Library Complex', 'evening'),
(385, 'Lawn Mowing', 'Open Lawn', 'morning'),
(386, 'Flower Arrangement', 'Vegetable Garden', 'morning'),
(387, 'Equipment Repair', 'Guest House', 'morning'),
(388, 'Drip System Setup', 'Recreation Area', 'morning'),
(389, 'Ground Cleaning', 'Parking Area', 'morning'),
(390, 'Perimeter Patrol', 'Main Gate Area', 'night'),
(391, 'Tree Planting', 'Tree Plantation Zone', 'morning'),
(392, 'Compost Mixing', 'Compost Area', 'morning'),
(393, 'Pest Spraying', 'Garden Area', 'evening'),
(394, 'Plant Watering', 'Flower Garden', 'morning'),
(395, 'Garden Design', 'Open Lawn', 'morning'),
(396, 'Supply Transport', 'Main Road', 'morning'),
(397, 'Irrigation Monitoring', 'Vegetable Garden', 'morning'),
(398, 'Waste Collection', 'Lecture Theatre area', 'morning'),
(399, 'Pruning', 'Tree Plantation Zone', 'morning'),
(400, 'Seed Sowing', 'Garden Area', 'morning');
