CREATE TABLE Sales_Details (
    Transaction_ID INT PRIMARY KEY,
    Item_Type VARCHAR(20) NOT NULL CHECK (Item_Type IN ('Fertilizer', 'Flower', 'Both')),
    Fertilizer_Name VARCHAR(50),
    Flower_Name VARCHAR(100),
    Quantity_Sold INT NOT NULL CHECK (Quantity_Sold >= 0),
    FOREIGN KEY (Transaction_ID) REFERENCES Sales_Header(Transaction_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (Fertilizer_Name) REFERENCES Fertilizer(Fertilizer_Name),
    FOREIGN KEY (Flower_Name) REFERENCES Flowers(Flower_Name),
    CHECK (
        (Item_Type = 'Fertilizer' AND Fertilizer_Name IS NOT NULL AND Flower_Name IS NULL) OR
        (Item_Type = 'Flower' AND Flower_Name IS NOT NULL AND Fertilizer_Name IS NULL) OR
        (Item_Type = 'Both' AND Fertilizer_Name IS NOT NULL AND Flower_Name IS NOT NULL)
    )
);

INSERT INTO Sales_Details (Transaction_ID, Item_Type, Fertilizer_Name, Flower_Name, Quantity_Sold) VALUES
(1, 'Fertilizer', 'Vermicompost', NULL, 50),
(2, 'Flower', NULL, 'Champo', 25),
(3, 'Both', 'Leaf Mold', 'Mogro', 30),
(4, 'Fertilizer', 'Kitchen Waste Compost', NULL, 40),
(5, 'Flower', NULL, 'Gulad', 35),
(6, 'Both', 'Garden Waste Fertilizer', 'Desi Gulab', 45),
(7, 'Fertilizer', 'Bio-compost', NULL, 25),
(8, 'Flower', NULL, 'Jui', 20),
(9, 'Both', 'Organic Mix', 'Jasud', 55),
(10, 'Fertilizer', 'Green Fertilizer', NULL, 35),
(11, 'Flower', NULL, 'Rajnigandha', 30),
(12, 'Both', 'Eco-fertilizer', 'Kaner', 40),
(13, 'Fertilizer', 'Organic Manure', NULL, 60),
(14, 'Flower', NULL, 'Genda', 45),
(15, 'Both', 'Plant Waste Compost', 'Aboli', 25),
(16, 'Fertilizer', 'Natural Fertilizer', NULL, 50),
(17, 'Flower', NULL, 'Parijat', 20),
(18, 'Both', 'Sustainable Compost', 'Shevanti', 35),
(19, 'Fertilizer', 'Green Waste Mix', NULL, 40),
(20, 'Flower', NULL, 'Kadamb', 15),
(21, 'Both', 'Vermicompost', 'Bakul', 30),
(22, 'Fertilizer', 'Leaf Mold', NULL, 45),
(23, 'Flower', NULL, 'Harsingar', 25),
(24, 'Both', 'Kitchen Waste Compost', 'Raat Rani', 20),
(25, 'Fertilizer', 'Garden Waste Fertilizer', NULL, 55),
(26, 'Flower', NULL, 'Kewda', 18),
(27, 'Both', 'Bio-compost', 'Chameli', 40),
(28, 'Fertilizer', 'Organic Mix', NULL, 35),
(29, 'Flower', NULL, 'Bela', 30),
(30, 'Both', 'Green Fertilizer', 'Kanher', 25),
(31, 'Fertilizer', 'Eco-fertilizer', NULL, 50),
(32, 'Flower', NULL, 'Galgoto', 60),
(33, 'Both', 'Organic Manure', 'Sadabahar', 45),
(34, 'Fertilizer', 'Plant Waste Compost', NULL, 40),
(35, 'Flower', NULL, 'Aparajita', 55),
(36, 'Both', 'Natural Fertilizer', 'Kohinoor', 35),
(37, 'Fertilizer', 'Sustainable Compost', NULL, 30),
(38, 'Flower', NULL, 'Chandni', 25),
(39, 'Both', 'Green Waste Mix', 'Champo', 20),
(40, 'Fertilizer', 'Vermicompost', NULL, 45),
(41, 'Flower', NULL, 'Mogro', 40),
(42, 'Both', 'Leaf Mold', 'Gulad', 30),
(43, 'Fertilizer', 'Kitchen Waste Compost', NULL, 50),
(44, 'Flower', NULL, 'Desi Gulab', 35),
(45, 'Both', 'Garden Waste Fertilizer', 'Jui', 25),
(46, 'Fertilizer', 'Bio-compost', NULL, 20),
(47, 'Flower', NULL, 'Jasud', 45),
(48, 'Both', 'Organic Mix', 'Rajnigandha', 30),
(49, 'Fertilizer', 'Green Fertilizer', NULL, 40),
(50, 'Flower', NULL, 'Kaner', 55),
(51, 'Both', 'Eco-fertilizer', 'Genda', 35),
(52, 'Fertilizer', 'Organic Manure', NULL, 50),
(53, 'Flower', NULL, 'Aboli', 25),
(54, 'Both', 'Plant Waste Compost', 'Parijat', 20),
(55, 'Fertilizer', 'Natural Fertilizer', NULL, 45),
(56, 'Flower', NULL, 'Shevanti', 30),
(57, 'Both', 'Sustainable Compost', 'Kadamb', 15),
(58, 'Fertilizer', 'Green Waste Mix', NULL, 40),
(59, 'Flower', NULL, 'Bakul', 25),
(60, 'Both', 'Vermicompost', 'Harsingar', 20),
(61, 'Fertilizer', 'Leaf Mold', NULL, 35),
(62, 'Flower', NULL, 'Raat Rani', 18),
(63, 'Both', 'Kitchen Waste Compost', 'Kewda', 15),
(64, 'Fertilizer', 'Garden Waste Fertilizer', NULL, 50),
(65, 'Flower', NULL, 'Chameli', 40),
(66, 'Both', 'Bio-compost', 'Bela', 25),
(67, 'Fertilizer', 'Organic Mix', NULL, 45),
(68, 'Flower', NULL, 'Kanher', 60),
(69, 'Both', 'Green Fertilizer', 'Galgoto', 35),
(70, 'Fertilizer', 'Eco-fertilizer', NULL, 30),
(71, 'Flower', NULL, 'Sadabahar', 70),
(72, 'Both', 'Organic Manure', 'Aparajita', 40),
(73, 'Fertilizer', 'Plant Waste Compost', NULL, 35),
(74, 'Flower', NULL, 'Kohinoor', 45),
(75, 'Both', 'Natural Fertilizer', 'Chandni', 25),
(76, 'Fertilizer', 'Sustainable Compost', NULL, 30),
(77, 'Flower', NULL, 'Champo', 20),
(78, 'Both', 'Green Waste Mix', 'Mogro', 35),
(79, 'Fertilizer', 'Vermicompost', NULL, 40),
(80, 'Flower', NULL, 'Gulad', 30),
(81, 'Both', 'Leaf Mold', 'Desi Gulab', 45),
(82, 'Fertilizer', 'Kitchen Waste Compost', NULL, 25),
(83, 'Flower', NULL, 'Jui', 35),
(84, 'Both', 'Garden Waste Fertilizer', 'Jasud', 20),
(85, 'Fertilizer', 'Bio-compost', NULL, 15),
(86, 'Flower', NULL, 'Rajnigandha', 25),
(87, 'Both', 'Organic Mix', 'Kaner', 50),
(88, 'Fertilizer', 'Green Fertilizer', NULL, 35),
(89, 'Flower', NULL, 'Genda', 40),
(90, 'Both', 'Eco-fertilizer', 'Aboli', 30),
(91, 'Fertilizer', 'Organic Manure', NULL, 55),
(92, 'Flower', NULL, 'Parijat', 15),
(93, 'Both', 'Plant Waste Compost', 'Shevanti', 35),
(94, 'Fertilizer', 'Natural Fertilizer', NULL, 40),
(95, 'Flower', NULL, 'Kadamb', 20),
(96, 'Both', 'Sustainable Compost', 'Bakul', 25),
(97, 'Fertilizer', 'Green Waste Mix', NULL, 45),
(98, 'Flower', NULL, 'Harsingar', 18),
(99, 'Both', 'Vermicompost', 'Raat Rani', 15),
(100, 'Fertilizer', 'Leaf Mold', NULL, 30),
(101, 'Flower', NULL, 'Kewda', 12),
(102, 'Both', 'Kitchen Waste Compost', 'Chameli', 40),
(103, 'Fertilizer', 'Garden Waste Fertilizer', NULL, 50),
(104, 'Flower', NULL, 'Bela', 35),
(105, 'Both', 'Bio-compost', 'Kanher', 20),
(106, 'Fertilizer', 'Organic Mix', NULL, 45),
(107, 'Flower', NULL, 'Galgoto', 55),	
(108, 'Both', 'Green Fertilizer', 'Sadabahar', 30),
(109, 'Fertilizer', 'Eco-fertilizer', NULL, 35),
(110, 'Flower', NULL, 'Aparajita', 45),
(111, 'Both', 'Organic Manure', 'Kohinoor', 40),
(112, 'Fertilizer', 'Plant Waste Compost', NULL, 25),
(113, 'Flower', NULL, 'Chandni', 30),
(114, 'Both', 'Natural Fertilizer', 'Champo', 35),
(115, 'Fertilizer', 'Sustainable Compost', NULL, 20),
(116, 'Flower', NULL, 'Mogro', 45),
(117, 'Both', 'Green Waste Mix', 'Gulad', 25),
(118, 'Fertilizer', 'Vermicompost', NULL, 50),
(119, 'Flower', NULL, 'Desi Gulab', 40),
(120, 'Both', 'Leaf Mold', 'Jui', 30),
(121, 'Fertilizer', 'Kitchen Waste Compost', NULL, 35),
(122, 'Flower', NULL, 'Jasud', 25),
(123, 'Both', 'Garden Waste Fertilizer', 'Rajnigandha', 20),
(124, 'Fertilizer', 'Bio-compost', NULL, 15),
(125, 'Flower', NULL, 'Kaner', 60),
(126, 'Both', 'Organic Mix', 'Genda', 45),
(127, 'Fertilizer', 'Green Fertilizer', NULL, 40),
(128, 'Flower', NULL, 'Aboli', 30),
(129, 'Both', 'Eco-fertilizer', 'Parijat', 18),
(130, 'Fertilizer', 'Organic Manure', NULL, 50),
(131, 'Flower', NULL, 'Shevanti', 35),
(132, 'Both', 'Plant Waste Compost', 'Kadamb', 15),
(133, 'Fertilizer', 'Natural Fertilizer', NULL, 45),
(134, 'Flower', NULL, 'Bakul', 25),
(135, 'Both', 'Sustainable Compost', 'Harsingar', 20),
(136, 'Fertilizer', 'Green Waste Mix', NULL, 40),
(137, 'Flower', NULL, 'Raat Rani', 16),
(138, 'Both', 'Vermicompost', 'Kewda', 12),
(139, 'Fertilizer', 'Leaf Mold', NULL, 35),
(140, 'Flower', NULL, 'Chameli', 45),
(141, 'Both', 'Kitchen Waste Compost', 'Bela', 30),
(142, 'Fertilizer', 'Garden Waste Fertilizer', NULL, 55),
(143, 'Flower', NULL, 'Kanher', 50),
(144, 'Both', 'Bio-compost', 'Galgoto', 25),
(145, 'Fertilizer', 'Organic Mix', NULL, 40),
(146, 'Flower', NULL, 'Sadabahar', 65),
(147, 'Both', 'Green Fertilizer', 'Aparajita', 35),
(148, 'Fertilizer', 'Eco-fertilizer', NULL, 30),
(149, 'Flower', NULL, 'Kohinoor', 40),
(150, 'Both', 'Organic Manure', 'Chandni', 25),
(151, 'Fertilizer', 'Plant Waste Compost', NULL, 45),
(152, 'Flower', NULL, 'Champo', 30),
(153, 'Both', 'Natural Fertilizer', 'Mogro', 35),
(154, 'Fertilizer', 'Sustainable Compost', NULL, 25),
(155, 'Flower', NULL, 'Gulad', 40),
(156, 'Both', 'Green Waste Mix', 'Desi Gulab', 45),
(157, 'Fertilizer', 'Vermicompost', NULL, 35),
(158, 'Flower', NULL, 'Jui', 20),
(159, 'Both', 'Leaf Mold', 'Jasud', 30),
(160, 'Fertilizer', 'Kitchen Waste Compost', NULL, 40),
(161, 'Flower', NULL, 'Rajnigandha', 25),
(162, 'Both', 'Garden Waste Fertilizer', 'Kaner', 50),
(163, 'Fertilizer', 'Bio-compost', NULL, 20),
(164, 'Flower', NULL, 'Genda', 45),
(165, 'Both', 'Organic Mix', 'Aboli', 35),
(166, 'Fertilizer', 'Green Fertilizer', NULL, 30),
(167, 'Flower', NULL, 'Parijat', 18),
(168, 'Both', 'Eco-fertilizer', 'Shevanti', 40),
(169, 'Fertilizer', 'Organic Manure', NULL, 55),
(170, 'Flower', NULL, 'Kadamb', 15),
(171, 'Both', 'Plant Waste Compost', 'Bakul', 20),
(172, 'Fertilizer', 'Natural Fertilizer', NULL, 50),
(173, 'Flower', NULL, 'Harsingar', 22),
(174, 'Both', 'Sustainable Compost', 'Raat Rani', 14),
(175, 'Fertilizer', 'Green Waste Mix', NULL, 45),
(176, 'Flower', NULL, 'Kewda', 10),
(177, 'Both', 'Vermicompost', 'Chameli', 35),
(178, 'Fertilizer', 'Leaf Mold', NULL, 30),
(179, 'Flower', NULL, 'Bela', 40),
(180, 'Both', 'Kitchen Waste Compost', 'Kanher', 55),
(181, 'Fertilizer', 'Garden Waste Fertilizer', NULL, 60),
(182, 'Flower', NULL, 'Galgoto', 70),
(183, 'Both', 'Bio-compost', 'Sadabahar', 25),
(184, 'Fertilizer', 'Organic Mix', NULL, 45),
(185, 'Flower', NULL, 'Aparajita', 50),
(186, 'Both', 'Green Fertilizer', 'Kohinoor', 30),
(187, 'Fertilizer', 'Eco-fertilizer', NULL, 35),
(188, 'Flower', NULL, 'Chandni', 28),
(189, 'Both', 'Organic Manure', 'Champo', 40),
(190, 'Fertilizer', 'Plant Waste Compost', NULL, 25),
(191, 'Flower', NULL, 'Mogro', 35),
(192, 'Both', 'Natural Fertilizer', 'Gulad', 45),
(193, 'Fertilizer', 'Sustainable Compost', NULL, 30),
(194, 'Flower', NULL, 'Desi Gulab', 50),
(195, 'Both', 'Green Waste Mix', 'Jui', 20),
(196, 'Fertilizer', 'Vermicompost', NULL, 40),
(197, 'Flower', NULL, 'Jasud', 35),
(198, 'Both', 'Leaf Mold', 'Rajnigandha', 25),
(199, 'Fertilizer', 'Kitchen Waste Compost', NULL, 35),
(200, 'Flower', NULL, 'Kaner', 65),
(201, 'Both', 'Garden Waste Fertilizer', 'Genda', 40),
(202, 'Fertilizer', 'Bio-compost', NULL, 18),
(203, 'Flower', NULL, 'Aboli', 30),
(204, 'Both', 'Organic Mix', 'Parijat', 15),
(205, 'Fertilizer', 'Green Fertilizer', NULL, 45),
(206, 'Flower', NULL, 'Shevanti', 45),
(207, 'Both', 'Eco-fertilizer', 'Kadamb', 12),
(208, 'Fertilizer', 'Organic Manure', NULL, 50),
(209, 'Flower', NULL, 'Bakul', 28),
(210, 'Both', 'Plant Waste Compost', 'Harsingar', 18),
(211, 'Fertilizer', 'Natural Fertilizer', NULL, 40),
(212, 'Flower', NULL, 'Raat Rani', 12),
(213, 'Both', 'Sustainable Compost', 'Kewda', 8),
(214, 'Fertilizer', 'Green Waste Mix', NULL, 35),
(215, 'Flower', NULL, 'Chameli', 50),
(216, 'Both', 'Vermicompost', 'Bela', 25),
(217, 'Fertilizer', 'Leaf Mold', NULL, 25),
(218, 'Flower', NULL, 'Kanher', 60),
(219, 'Both', 'Kitchen Waste Compost', 'Galgoto', 55),
(220, 'Fertilizer', 'Garden Waste Fertilizer', NULL, 65),
(221, 'Flower', NULL, 'Sadabahar', 80),
(222, 'Both', 'Bio-compost', 'Aparajita', 30),
(223, 'Fertilizer', 'Organic Mix', NULL, 50),
(224, 'Flower', NULL, 'Kohinoor', 45),
(225, 'Both', 'Green Fertilizer', 'Chandni', 20);
