CREATE TABLE Tree_Species (
    Common_Name VARCHAR(100) PRIMARY KEY,
    Botanical_Name VARCHAR(150) NOT NULL,
    Water_Req VARCHAR(20) CHECK (Water_Req IN ('Low', 'Medium', 'High')),
    Fertilizer_Name VARCHAR(50),
    FOREIGN KEY (Fertilizer_Name) REFERENCES Fertilizer(Fertilizer_Name)
);


INSERT INTO Tree_Species (Common_Name, Botanical_Name, Water_Req, Fertilizer_Name) VALUES
('Bengali Babool', 'Acacia auriculiformis A. Cunn. ex Benth.', 'Low', 'Vermicompost'),
('Khair', 'Acacia catechu Willd.', 'Low', 'Leaf Mold'),
('Safed Babul', 'Acacia leucophloea Willd.', 'Low', 'Kitchen Waste Compost'),
('Desi Babul', 'Acacia nilotica (L.) Willd. ex Del.', 'Low', 'Garden Waste Fertilizer'),
('Billi Patra', 'Aegle marmelos L. Correa', 'Medium', 'Bio-compost'),
('Arduso', 'Ailanthus excelsa Roxb.', 'Low', 'Organic Mix'),
('Kalo Siras', 'Albizia odoratissima (L.f.) Benth.', 'Medium', 'Green Fertilizer'),
('Saptparni', 'Alstonia scholaris R. Br.', 'Medium', 'Eco-fertilizer'),
('Sitaphal', 'Annona squamosa (L.)', 'Medium', 'Organic Manure'),
('Limbdo', 'Azadirachta indica A. Juss.', 'Low', 'Plant Waste Compost'),
('Ingoriya', 'Balanites aegyptiaca (L.) Delile', 'Low', 'Natural Fertilizer'),
('Kanchanar', 'Bauhinia purpurea L.', 'Medium', 'Sustainable Compost'),
('Yellow Bauhinia', 'Bauhinia tomentosa L.', 'Low', 'Green Waste Mix'),
('Bismarckia', 'Bismarckia nobilis Hildebr. & Wendl.', 'High', 'Vermicompost'),
('Shimalo', 'Bombax ceiba L.', 'Medium', 'Leaf Mold'),
('Kesudo', 'Butea monosperma (Lamk) Taub.', 'Low', 'Kitchen Waste Compost'),
('Dwarf Gulmohar', 'Caesalpinia pulcherrima (L.) Sw.', 'Medium', 'Garden Waste Fertilizer'),
('Powder Crop', 'Calliandra haematocephala Hassk.', 'Medium', 'Bio-compost'),
('Australian Bottle Brush', 'Callistemon acuminatus R. Br.', 'Medium', 'Organic Mix'),
('Karamda', 'Carissa carandas L.', 'Low', 'Green Fertilizer'),
('Shivjata', 'Caryota urens L.', 'High', 'Eco-fertilizer'),
('Yellow Karen', 'Cascabela thevetia (L.) Lippold', 'Low', 'Organic Manure'),
('Garmalo', 'Cassia fistula Linn.', 'Medium', 'Plant Waste Compost'),
('Pink Cassia', 'Cassia renigera Benth.', 'Medium', 'Natural Fertilizer'),
('Kapok', 'Ceiba pentandra (L.) Gaertn.', 'Medium', 'Sustainable Compost'),
('Mosambi', 'Citrus limetta Risso', 'High', 'Green Waste Mix'),
('Limbu', 'Citrus limon L.', 'High', 'Vermicompost'),
('Arni', 'Clerodendrum phlomidis L. f.', 'Medium', 'Leaf Mold'),
('Gundo', 'Cordia dichotoma Forst. F.', 'Low', 'Kitchen Waste Compost'),
('Lal Lasora', 'Cordia sebestena L.', 'Medium', 'Garden Waste Fertilizer'),
('Kailash Pati', 'Couroupita guianensis Aubl.', 'High', 'Bio-compost'),
('Dalbergia', 'Dalbergia cochinchinensis Pierre ex Laness.', 'Medium', 'Organic Mix'),
('Sisoo', 'Dalbergia sisso Roxb. ex DC.', 'Medium', 'Green Fertilizer'),
('Gulmohar', 'Delonix regia (Boj) Raf.', 'Medium', 'Eco-fertilizer'),
('Putranjiva', 'Drypetes roxburghii (Wall.) Hurus.', 'Medium', 'Organic Manure'),
('Oil Palm', 'Elaeis guineensis Jacq.', 'High', 'Plant Waste Compost'),
('Amla', 'Emblica officinalis Gaertn.', 'Medium', 'Natural Fertilizer'),
('Pangaro', 'Erythrina variegata L. var.', 'Medium', 'Sustainable Compost'),
('Fatsia Polycarpa', 'Fatsia polycarpa Hayata', 'High', 'Green Waste Mix'),
('Vad', 'Ficus benghalensis L.', 'Medium', 'Vermicompost'),
('Benjamina', 'Ficus benjamina L.', 'Medium', 'Leaf Mold'),
('Ficus Longifolia', 'Ficus longifolia Schott', 'Medium', 'Kitchen Waste Compost'),
('Nandrak Vad', 'Ficus microcarpa L. f.', 'Medium', 'Garden Waste Fertilizer'),
('Umro', 'Ficus racemosa L.', 'Medium', 'Bio-compost'),
('Piplo', 'Ficus religiosa L. Forssk.', 'Medium', 'Organic Mix'),
('Gliricidia', 'Gliricidia sepium (Jacq.) Steud.', 'Low', 'Green Fertilizer'),
('Sevan', 'Gmelina arborea L.', 'Medium', 'Eco-fertilizer'),
('Silver Oak', 'Grevillea robusta A. Cunn.', 'Medium', 'Organic Manure'),
('Hippomane', 'Hippomane mancinella L.', 'Medium', 'Plant Waste Compost'),
('Indrajau', 'Holarrhena antidysenterica var. macrantha Kerr', 'Medium', 'Natural Fertilizer'),
('Kanji', 'Holoptelea integrifolia Planch.', 'Low', 'Sustainable Compost'),
('Cucumber Tree', 'Kigelia pinnata (Jacq.)', 'Medium', 'Green Waste Mix'),
('Bondaro', 'Lagerstroemia speciosa (L.) Pers.', 'Medium', 'Vermicompost'),
('Fan Palm', 'Latania lontaroides (Gaertner) H. E. Moore', 'High', 'Leaf Mold'),
('Subabul', 'Leucaena leucocephala (Lam) de Wit', 'Low', 'Kitchen Waste Compost'),
('Kothi', 'Limonia acidissima L.', 'Medium', 'Garden Waste Fertilizer'),
('Livistonia Mariea', 'Livistona mariae F.Muell.', 'High', 'Bio-compost'),
('Mahudo', 'Madhuca longifolia Macb.', 'Medium', 'Organic Mix'),
('Champo', 'Magnolia champaca (L.) Baill. Ex Pierre', 'High', 'Green Fertilizer'),
('Ambo', 'Mangifera indica (L.)', 'High', 'Eco-fertilizer'),
('Rayan', 'Manilkara hexandra (Roxb.)', 'Medium', 'Organic Manure'),
('Bakan Neem', 'Melia azedarach L.', 'Low', 'Plant Waste Compost'),
('Nimbara', 'Melia dubia Cav.', 'Low', 'Natural Fertilizer'),
('Borsalli', 'Mimusops elengi L.', 'Medium', 'Sustainable Compost'),
('Kalam', 'Mitragyna parvifolia (Roxb.) Korth.', 'Medium', 'Green Waste Mix'),
('Mitho Limdo', 'Murraya koenigii (L.) Sprengel', 'Medium', 'Vermicompost'),
('Kunti', 'Murraya paniculata (L.) Jack', 'Medium', 'Leaf Mold'),
('Kadam', 'Neolamarckia cadamba (Roxb.) Bosser', 'High', 'Kitchen Waste Compost'),
('Parijat', 'Nyctanthus arbortristis L.', 'Medium', 'Garden Waste Fertilizer'),
('Parkia', 'Parkia roxburghii G. Don', 'Medium', 'Bio-compost'),
('Sonmohor', 'Peltophorum pterocarpum (DC.) K. Heyne', 'Medium', 'Organic Mix'),
('Khajuri', 'Phoenix sylvestris (L.) Roxb.', 'Medium', 'Green Fertilizer'),
('Mithi Ambali', 'Pithecellobium dulce (Roxb.) Benth.', 'Low', 'Eco-fertilizer'),
('Asopalav', 'Polyalthia longifolia Sonn.', 'Medium', 'Organic Manure'),
('Karanj', 'Pongamia pinnata (L.) Pierre', 'Low', 'Plant Waste Compost'),
('Khijado', 'Prosopis cineraria Druce.', 'Low', 'Natural Fertilizer'),
('Gando Baval', 'Prosopis juliflora (Swartz) DC.', 'Low', 'Sustainable Compost'),
('Jamphal', 'Psidium guajava L.', 'Medium', 'Green Waste Mix'),
('Kanak Champo', 'Pterospermum acerifolium L. Wild.', 'Medium', 'Vermicompost'),
('Pilu', 'Salvadora oleoides Decne.', 'Low', 'Leaf Mold'),
('Rato-Sarasdo', 'Samanea saman (Jacq.) Merr.', 'Medium', 'Kitchen Waste Compost'),
('Aritha', 'Sapindus mukorossi Gaertn.', 'Medium', 'Garden Waste Fertilizer'),
('Kashid', 'Senna siamea (Lam.) Irwin et Barneby', 'Low', 'Bio-compost'),
('Spathodea', 'Spathodea campanulata P. Beauv.', 'Medium', 'Organic Mix'),
('Harero', 'Steblus asper Lour.', 'Low', 'Green Fertilizer'),
('Jangli Badam', 'Sterculia foetida L.', 'Medium', 'Eco-fertilizer'),
('Mahagony', 'Swietenia mahagoni (Linn.) Jacq.', 'Medium', 'Organic Manure'),
('Jambu', 'Syzygium cumini L. Skeels.', 'Medium', 'Plant Waste Compost'),
('Tabebuia Aurea', 'Tabebuia aurea (Silva Manso) Benth. & Hook. F. ex S. Moore', 'Medium', 'Natural Fertilizer'),
('Tabebuia Rosea', 'Tabebuia rosea DC.', 'Medium', 'Sustainable Compost'),
('Khati Amali', 'Tamarindus indica L.', 'Low', 'Green Waste Mix'),
('Ragat Rohida', 'Tecomella undulata (Smith) Seem.', 'Low', 'Vermicompost'),
('Arjun Sadad', 'Terminalia arjuna (Roxb. ex DC.) Wight. & Arn.', 'Medium', 'Leaf Mold'),
('Baheda', 'Terminalia bellirica Roxb.', 'Medium', 'Kitchen Waste Compost'),
('Desi Badam', 'Terminalia catappa L.', 'Medium', 'Garden Waste Fertilizer'),
('Harde', 'Terminalia chebula Retz.', 'Medium', 'Bio-compost'),
('Paras Piplo', 'Thespesia populnea (L.) Sol. ex Correa', 'Medium', 'Organic Mix'),
('Nagod', 'Vitex negundo L.', 'Low', 'Green Fertilizer'),
('Bougainvillea', 'Bougainvillea spectabilis Comm. Ex Juss.', 'Low', 'Eco-fertilizer'),
('Hemalia', 'Hamalia patens Jacq.', 'Medium', 'Organic Manure'),
('Jacaranda', 'Jacaranda mimosaefolia D. Don.', 'Medium', 'Plant Waste Compost'),
('Jatropha', 'Jatropha gossypiifolia L.', 'Low', 'Natural Fertilizer'),
('Pavetta', 'Pavetta indica L.', 'Medium', 'Sustainable Compost'),
('Tagar', 'Tabernaemontana divaricata R. Br. ex Roem. & Schult.', 'Medium', 'Green Waste Mix'),
('Tecoma', 'Tecoma stans (L.) Juss. ex Kunth', 'Low', 'Vermicompost'),
('Ketki', 'Agave americana L.', 'Low', 'Leaf Mold'),
('Bamboo', 'Bambusa striata Lodd. ex Lindl.', 'High', 'Kitchen Waste Compost');
